---
title: "Data for Final Project"
author: "Ruy Martinez"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

```{r}
pop <- read.csv("data/2010racepop.csv") %>%
  mutate(whitepercent = WHITE / TOTAL,
         blackpercent = BLACK / TOTAL,
         aianpercent = AIAN / TOTAL,
         asianpercent = ASIAN / TOTAL,
         nhpipercent = NHPI / TOTAL,
         otherpercent = OTHER / TOTAL,
         mixedpercent = MIXED / TOTAL,
         latinopercent = LATINO / TOTAL) %>%
  pivot_longer(cols = whitepercent:latinopercent, 
               names_to = "race", values_to = "proportion") %>%
  saveRDS("app_files/population_proportions.RDS")
  
# These are calculating the percent, or proportion, of the population. This is
# easier to graph and to understand compared to raw numbers. We save this
# as an RDS to not deal with the readr mess in terms of CSVs. It's also just
# a lot cleaner for people to download.
```


```{r}
covidrace <- read_csv("data/race_dat.csv",
                      na = "",
                      col_types = cols(Cases_White = "i",
                                       Cases_Total = "i",
                                       State = col_factor())) %>%
  
# Column setting and making sure State is a factor, not a character. This lets
# us rename the levels later when we graph.
  
  mutate(Date = lubridate::ymd(Date)) %>%
  
# A date should be a date! Might turn this into a character later since the
# selectors on Shiny are easier to understand if I do that.
  
  mutate(caseper_white = Cases_White / Cases_Total,
         caseper_black = Cases_Black / Cases_Total,
         caseper_latino = Cases_LatinX / Cases_Total,
         caseper_asian = Cases_Asian / Cases_Total,
         caseperaian = Cases_AIAN / Cases_Total,
         casepernhpi = Cases_NHPI / Cases_Total,
         casepermulti = Cases_Multiracial / Cases_Total,
         caseperother = Cases_Other / Cases_Total,
         caseperunkn = Cases_Unknown / Cases_Total,
         caseperhispanic = Cases_Ethnicity_Hispanic / Cases_Total,
         casepernonhis = Cases_Ethnicity_NonHispanic / Cases_Total,
         deathper_white = Deaths_White / Deaths_Total,
         deathper_black = Deaths_Black / Deaths_Total,
         deathper_latino = Deaths_LatinX / Deaths_Total,
         deathper_asian = Deaths_Asian / Deaths_Total,
         deathperaian = Deaths_AIAN / Deaths_Total,
         deathpernhpi = Deaths_NHPI / Deaths_Total,
         deathpermulti = Deaths_Multiracial / Deaths_Total,
         deathperother = Deaths_Other / Deaths_Total,
         deathperunkn = Deaths_Unknown / Deaths_Total,
         deathperhispanic = Deaths_Ethnicity_Hispanic / Deaths_Total,
         deathpernonhis = Deaths_Ethnicity_NonHispanic / Deaths_Total,
         deathperethunk = Deaths_Ethnicity_Unknown / Deaths_Total)

# All the percentages! This is annoying but necessary to be able to graph our
# data in a useful manner. I can then make a raw numbers graph later if I want.

covid_race_cases <- covidrace %>%
  select(Date:State, caseper_white:caseperunkn) %>%
  pivot_longer(cols = caseper_white:caseperunkn, 
               names_to = "race_c", values_to = "cases_r") %>%
  mutate(race = str_remove(race_c, "caseper"))

# This is a ton of data, so it's easier to graph if we pivot longer one set at a
# time. Joining these together will be a nightmare, but I'll deal with that
# when I get to it.

covid_ethnicity_cases <- covidrace %>%
  select(Date:State, Cases_Ethnicity_Hispanic:Cases_Ethnicity_Unknown)

# A bit of useful help if someone wants to begin going through the ethnicity 
# aspect of the data!

covid_race_deaths <- covidrace %>%
  select(Date:State, deathper_white:deathperunkn) %>%
  pivot_longer(cols = deathper_white:deathperunkn,
               names_to = "race_d", values_to = "deaths_r") %>%
  mutate(race = str_remove(race_d, "deathper"))

# We are pivotting all the deaths with only the racial columns, not ethnicity.

covid_ethnicity_deaths <- covidrace %>%
  select(Date:State, Deaths_Ethnicity_Hispanic:Deaths_Ethnicity_Unknown)

# These are all basically the same and will be pivoted in a similar fashion
# later.

covid_race_cases_deaths <- left_join(covid_race_cases, covid_race_deaths,
                                     by = c("Date", "State", "race")) %>%
  pivot_longer(cols = c("cases_r", "deaths_r"),
               names_to = "caseordeath", values_to = "number") %>%
  saveRDS("app_files/covid_race_cases_deaths.RDS")

# The data from the race cases and deaths are now joined for one super long
# table that we can utilize for our very interactive data visualization!

```
